Traceback (most recent call last):
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 754, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 801, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['weights = jnp.ones((n_datasets,)) / n_datasets', '', 'means = jnp.stack([d.mean() for d in posterior_preds])', 'barycentre_mean = jnp.tensordot(weights, means, axes=1)', '']
...
['    step_fn, initial_covariance, jnp.arange(100)', ')', 'L = jnp.linalg.cholesky(barycentre_covariance)', '', 'barycentre_process = dx.MultivariateNormalTri(barycentre_mean, L)']
-------------------

